name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /projects/shortify
            sudo sh .dev/restart.sh
